//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Animal
    {
               [Key]
            public int Animal_ID { get; set; }
    
        public string Animal_Name { get; set; }
    
        public string Animal_Sex { get; set; }
    
        public Nullable<System.DateTime> Animal_DOB { get; set; }
    
        public string Species { get; set; }
    
        public Nullable<int> Weight { get; set; }
    
        public string Diet { get; set; }
    
        public Nullable<System.DateTime> Arrival_date { get; set; }
    
        public int Enclosure_ID { get; set; }
    
        public string Medical_notes { get; set; }
    
        public string Endangered_status { get; set; }
    
        public Nullable<System.TimeSpan> Feeding_time { get; set; }
    
        public int Zookeeper_ID { get; set; }
    
    
        public virtual Zookeeper Zookeeper { get; set; }
        public virtual Enclosure Enclosure { get; set; }
    }
}
