//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Closing
    {
               [Key]
            public int Closing_ID { get; set; }
    
        public System.DateTime Closings_end { get; set; }
    
        public System.DateTime Closings_start { get; set; }
    
        public string Closings_reason { get; set; }
    
        public int Enclosure_ID { get; set; }
    
    
        public virtual Enclosure Enclosure { get; set; }
    }
}
