//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Food_store = new HashSet<Food_store>();
            this.Gift_shop = new HashSet<Gift_shop>();
        }
    
               [Key]
            public int Customer_ID { get; set; }
    
        public string Customer_First_name { get; set; }
    
        public string Customer_Last_name { get; set; }
    
        public Nullable<System.DateTime> Customer_DOB { get; set; }
    
        public string Customer_Address { get; set; }
    
        public System.DateTime Membership_start_date { get; set; }
    
        public System.DateTime Membership_end_date { get; set; }
    
        public string Membership_type { get; set; }
    
        public string Customer_Email { get; set; }
    
        public string Customer_Password { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_store> Food_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift_shop> Gift_shop { get; set; }
    }
}
