//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Dependant
    {
               [Key]
            public int Depndant_ID { get; set; }
    
        public int Employee_ID { get; set; }
    
        public string Dependent_Name { get; set; }
    
        public string Dependent_Sex { get; set; }
    
        public Nullable<System.DateTime> Dependent_DOB { get; set; }
    
        public string Relationship { get; set; }
    
        public string Healthcare_tier { get; set; }
    
    
        public virtual Employee Employee { get; set; }
    }
}
