//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Dependants = new HashSet<Dependant>();
            this.Events = new HashSet<Event>();
            this.Managers = new HashSet<Manager>();
            this.Zookeepers = new HashSet<Zookeeper>();
        }
    
        [Key]
        [Display(Name = "Employee ID")]
        public int Employee_ID { get; set; }
    
        public int SSN { get; set; }

        [Display(Name = "First Name")]
        public string Employee_First_name { get; set; }

        [Display(Name = "Last Name")]
        public string Employee_Last_name { get; set; }

        [Display(Name = "DOB")]
        public Nullable<System.DateTime> Employee_DOB { get; set; }

        [Display(Name = "Address")]
        public string Employee_Address { get; set; }

        [Display(Name = "Salary")]
        public Nullable<int> Employee_Salary { get; set; }

        [Display(Name = "Hire Date")]
        [Required]
        public Nullable<System.DateTime> Date_of_employment { get; set; }

        private string degree;

        public string GetDegree()
        {
            return degree;
        }

        public void SetDegree(string value)
        {
            degree = value;
        }

        [Display(Name = "Phone Num")]
        public string Employee_Phone_number { get; set; }

        [Display(Name = "Supervisor's ID")]
        public Nullable<int> Supervisor_ID { get; set; }
    
        public string Department { get; set; }

        [Display(Name = "Associated Gift Shop ID")]
        public Nullable<int> Shop_ID { get; set; }

        [Display(Name = "Associated Food Shop ID")]
        public Nullable<int> Food_store_ID { get; set; }
    
        public string Employee_Password { get; set; }

        [Required]
        [Display(Name = "Role")]
        public string role { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dependant> Dependants { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Gift_shop Gift_shop { get; set; }
        public virtual Food_store Food_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zookeeper> Zookeepers { get; set; }
    }
}
