//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Food_store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food_store()
        {
            this.Employees = new HashSet<Employee>();
            this.Customers = new HashSet<Customer>();
            this.Items = new HashSet<Item>();
        }
    
               [Key]
            public int Food_store_ID { get; set; }
    
        public string Food_store_name { get; set; }
    
        public string Food_store_location { get; set; }
    
        public Nullable<System.TimeSpan> Food_store_open_time { get; set; }
    
        public Nullable<System.TimeSpan> Food_store_close_time { get; set; }
    
        public Nullable<int> Food_store_customer_capacity { get; set; }
    
        public string Food_store_type { get; set; }
    
        public int Food_store_year_to_date_sales { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
