//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Food_store = new HashSet<Food_store>();
            this.Gift_shop = new HashSet<Gift_shop>();
        }
    
               [Key]
            public int item_ID { get; set; }
    
        public string Item_name { get; set; }
    
        public int Item_count { get; set; }
    
        public System.DateTime Restock_date { get; set; }
    
        public Nullable<int> Shop_ID { get; set; }
    
        public Nullable<int> Food_store_ID { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_store> Food_store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gift_shop> Gift_shop { get; set; }
    }
}
