//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
               [Key]
            public int Purchase_ID { get; set; }
    
        public Nullable<int> Customer_ID { get; set; }
    
        public Nullable<int> Store_ID { get; set; }
    
        public Nullable<int> num_items { get; set; }
    
        public Nullable<int> Total_purchases_price { get; set; }
    
        public Nullable<System.DateTime> Purchase_date { get; set; }
    
        public string Purchase_method { get; set; }
    
        public Nullable<System.TimeSpan> Purchase_time { get; set; }
    
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
