//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Zookeeper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zookeeper()
        {
            this.Animals = new HashSet<Animal>();
            this.Enclosures = new HashSet<Enclosure>();
        }
    
               [Key]
            public int Zookeeper_ID { get; set; }
    
        public int Employee_ID { get; set; }
    
        public Nullable<short> Num_Assigned_cages { get; set; }
    
        public Nullable<System.DateTime> Training_renewal_date { get; set; }
    
        public Nullable<System.DateTime> Last_training_date { get; set; }
    
        public string Assigned_department { get; set; }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enclosure> Enclosures { get; set; }
    }
}
